# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # checking for syntax
      - id: check-yaml
      - id: check-toml
      - id: check-json
      # simple formatting
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      # checks for unresolved merge conflicts
      - id: check-merge-conflict
  # sort python imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  # format f strings
  - repo: https://github.com/ikamensh/flynt/
    rev: "0.76"
    hooks:
      - id: flynt
  # format python code
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  # format markdown, yaml, json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude_types: [python]
        args: ["--print-width", "100"]
  # format java. Seperate from the above for different tab width
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: prettier-java
        types: [java]
        additional_dependencies:
          - prettier
          - prettier-plugin-java
        args: ["--tab-width", "4", "--print-width", "100"]
  # lint python code
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        # check for dead code
        additional_dependencies:
          - flake8-eradicate
          - flake8-bugbear
          - flake8-simplify
          - flake8-builtins
          - flake8-comprehensions
          - flake8-fixme
          - flake8-use-fstring
  #          - flake8-docstrings
  #          - flake8-rst-docstrings
  #          - darglint

  # lint markdown
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.7
    hooks:
      - id: pymarkdown
        args: ["-d", "md013,md034,md033,md036", "scan", "README.md"]
  # check config files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.17.1
    hooks:
      - id: check-gitlab-ci
      - id: check-readthedocs
  # linting for rst files
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.0.0.post1
    hooks:
      - id: rstcheck
        additional_dependencies:
          - rstcheck[sphinx]
          - rstcheck[toml]
