# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    - id: autopep8
      args: ["--select=E1,E2,E3,E401,W1,W2,W3,E226,E24", "--in-place", "--recursive", "."]

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: autopep8
        name: autopep8
        stages: [commit]
        language: system
        entry: pipenv run autopep8 --select=E1,E2,E3,E401,W1,W2,W3,E226,E24 --in-place --recursive .
        types: [python]
        exclude: setup.py

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: pipenv run pylint
        types: [python]
        exclude: setup.py
