# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # checking for syntax
      - id: check-yaml
      - id: check-toml
      - id: check-json
      # simple formatting
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      # checks for unresolved merge conflicts
      - id: check-merge-conflict
  # sort python imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  # format python code
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  # lint python code
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        # check for dead code
        additional_dependencies: [flake8-eradicate, flake8-bugbear, flake8-simplify, flake8-builtins]
  # format markdown, yaml, json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude_types: [python]
        args: ["--print-width", "100"]
  # format java. Seperate from the above for different tab width
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: prettier-java
        types: [java]
        additional_dependencies:
          - prettier
          - prettier-plugin-java
        args: ["--tab-width", "4", "--print-width", "100"]
