# File: .readthedocs.yaml

version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.7
  install:
    - requirements: docs/rtd_requirements.txt

sphinx:
  fail_on_warning: true

formats:
  - pdf
  - epub